Repository TicketSwap/solar, pull requests merged in 2019-06, with the labels that each got.

#140 Fix line-height issues with multiple checkbox elements
  src/components/Checkbox/index.js
Labels: ready for review

#141 fix(Checkbox): onChange handler
  src/components/Checkbox/index.js
  src/components/Checkbox/index.stories.js
Labels: ready for review

#142 fix(Checkbox): Allow to be controlled
  src/components/Checkbox/index.js
  src/components/Checkbox/index.stories.js
  src/components/Toggle/index.stories.js
Labels: ready for review

#170 Added new Twitter color
  src/theme.js
Labels: ready to merge

#179 fix(Input): Disable default appearance for time inputs
  src/components/Input/index.js
Labels: first approval, ready for review

#180 fix(useDeviceInfo): SSR compat
  src/hooks/useDeviceInfo.js
Labels: first approval, ready for review

#184 Collocate menu and Input
  src/components/CountrySelect/index.js
  src/components/Input/index.js
  src/components/Select/index.js
  src/index.js
Labels: first approval, ready for review

#186 Add PhoneInput component
  src/components/DateInput/index.js
  src/components/MoneyInput/index.js
  src/components/PhoneInput/index.js
  src/components/PhoneInput/index.stories.js
  src/components/Select/index.js
Labels: ready to merge

#199 Update Twitter colors
  src/components/MoneyInput/index.js
  src/components/PhoneInput/index.js
  src/theme.js
Labels: ready for review

#207 fix: select dropdown style fixes
  src/components/Input/index.js
  src/components/PhoneInput/index.js
  src/components/PhoneInput/index.stories.js
Labels: first approval, ready for review
