Repository TicketSwap/solar, pull requests merged in 2019-09, with the labels that each got.

#322 feat(useTransition): change return value
  src/components/ContentTransition/index.js
  src/components/Dialog/index.js
  src/components/MenuButton/index.js
  src/hooks/useTransition.js
  test/setup-tests.js
Labels: ready for review

#324 fix(contenttransition): change handling of active and previous index
  src/components/ContentTransition/index.js
  src/components/ContentTransition/index.stories.js
  src/hooks/useTransition.js
Labels: ready for review

#337 Add BaseButton component
  src/components/BaseButton/index.js
  src/components/BaseButton/index.stories.js
  src/index.js
Labels: first approval, ready for review

#339 fix(horizontal scroll): hide scroll on HorizontalScroll component
  src/components/HorizontalScroll/index.js
Labels: first approval, ready for review

#348 Allow click and key-handlers for on-controlled dialogs
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: first approval, ready for review

#347 fix(alert): Add default action
  src/components/Alert/index.js
  src/components/Alert/index.stories.js
Labels: ready to merge

#349 TTN-1702 improve alert action
  src/components/Alert/index.js
Labels: first approval, ready for review

#351 Update stories to use new Component Story Format
  .storybook/config.js
  src/components/Alert/index.stories.js
  src/components/Avatar/index.stories.js
  src/components/Banner/index.stories.js
  src/components/BaseButton/index.stories.js
  src/components/BasicCard/index.stories.js
  src/components/BasicCarousel/index.stories.js
  src/components/Button/index.stories.js
  src/components/Checkbox/index.stories.js
  src/components/ContentTransition/index.stories.js
  src/components/CountryInput/index.stories.js
  src/components/Cover/index.stories.js
  src/components/DateInput/index.stories.js
  src/components/Dialog/index.stories.js
  src/components/Flag/index.stories.js
  src/components/Heading/index.stories.js
  src/components/HorizontalScroll/index.stories.js
  src/components/Icon/index.stories.js
  src/components/Image/index.stories.js
  src/components/Input/index.stories.js
  src/components/Logo/index.stories.js
  src/components/MenuButton/index.stories.js
  src/components/MoneyInput/index.stories.js
  src/components/PhoneInput/index.stories.js
  src/components/Select/index.stories.js
  src/components/Spinner/index.stories.js
  src/components/StarRating/index.stories.js
  src/components/TabsGroup/index.stories.js
  src/components/Text/index.stories.js
  src/components/TimeInput/index.stories.js
  src/components/Toast/index.stories.js
  src/components/Toggle/index.stories.js
Labels: ready for review

#358 refactor: Cleanup alert component
  src/components/Alert/index.js
  src/components/Alert/index.stories.js
  src/components/Alert/index.test.js
Labels: first approval, ready for review

#359 Add Panel and Pill components
  src/components/Panel/index.js
  src/components/Panel/index.stories.js
  src/components/Pill/index.js
  src/components/Pill/index.stories.js
  src/index.js
Labels: first approval, ready for review
