Repository TicketSwap/solar, pull requests merged in 2019-11, with the labels that each got.

#419 build: update deps
  package.json
  src/components/Toast/index.stories.js
  yarn.lock
Labels: ready for review

#420 HorizontalScroll: Prevent history-navigation
  src/components/HorizontalScroll/index.js
Labels: first approval, ready for review

#421 Checkbox: Fix props-error
  src/components/Checkbox/index.js
Labels: first approval, ready for review

#437 New Card component
  src/components/BasicCard/index.js
  src/components/Card/index.js
  src/components/Card/index.stories.js
Labels: first approval, ready for review

#438 fix(Button): change disabled style
  src/components/Button/index.js
Labels: first approval, ready for review

#439 fix(CountryInput): add check for isLowerCase
  src/components/CountryInput/index.js
Labels: first approval, ready for review

#469 Remove overflow hidden from panel component
  src/components/Panel/index.js
  src/components/Panel/index.stories.js
Labels: ready to merge
