Repository TicketSwap/solar, pull requests merged in 2019-04, with the labels that each got.

#55 With updated Button component
  package-lock.json
  package.json
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/global-styles.js
  src/theme.js
Labels: ready to merge

#56 fix(Button): Fix focus styling
  src/components/Button/index.js
  src/global-styles.js
Labels: first approval, ready for review

#57 fix: Fix focus button styling in Alert, BasicCarousel and MenuButton
  src/components/Alert/index.js
  src/components/BasicCarousel/index.js
  src/components/MenuButton/index.js
Labels: ready for review

#58 Fixes a bug where disabled buttons were clickable in Safari
  src/components/Button/index.js
  src/components/Button/index.stories.js
Labels: ready for review

#59 Add Select component
  __tests__/CountrySelect.js
  __tests__/Select.js
  package-lock.json
  package.json
  src/components/CountrySelect/index.js
  src/components/CountrySelect/index.stories.js
  src/components/Dialog/index.js
  src/components/Input/index.js
  src/components/Select/index.js
  src/components/Select/index.stories.js
  src/index.js
Labels: first approval, ready for review

#60 feat(Icon): Add notification and sell glyphs
  src/components/Icon/index.js
Labels: ready to merge

#61 fix(Select): Fix prop forwarding
  src/components/Select/index.js
Labels: ready to merge

#62 Update Select arrow icon
  package-lock.json
  package.json
  src/components/Icon/index.js
  src/components/Select/index.js
Labels: first approval, ready for review

#63 Downgrade `babel-eslint`
  package-lock.json
  package.json
Labels: first approval, ready for review

#64 Increase padding on full-width buttons with icon
  src/components/Button/index.js
Labels: first approval, ready for review

#65 fix(Button): Don't allow button to be clicked when loading
  src/components/Button/index.js
Labels: ready to merge

#67 Remove gesture-control from BasicCarousel
  src/components/BasicCarousel/index.js
  src/components/BasicCarousel/index.stories.js
  src/components/Carousel/index.js
  src/components/Gesture/index.js
Labels: first approval, ready for review

#66 Add DateInput component
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/DateInput/index.js
  src/components/DateInput/index.stories.js
  src/components/Input/index.js
  src/components/Input/index.stories.js
  src/components/Select/index.js
  src/hooks/index.js
  src/hooks/useDeviceInfo.js
  src/index.js
  src/utils.js
Labels: ready to merge

#69 Replace `css`-prop usage with inline-styles
  src/components/Dialog/index.stories.js
  src/components/Image/index.stories.js
  src/components/MenuButton/index.stories.js
  src/components/Toast/index.stories.js
Labels: first approval, ready for review

#70 Refactor Select
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/components/Input/index.js
  src/components/Select/index.js
  src/hooks/useDeviceInfo.js
Labels: ready to merge

#68 Add Toggle component
  src/components/Toggle/Switch.js
  src/components/Toggle/index.js
  src/components/Toggle/index.stories.js
  src/index.js
  src/theme.js
Labels: ready to merge

#71 Add helper text and input props
  src/components/DateInput/index.js
  src/components/DateInput/index.stories.js
  src/components/Input/index.js
  src/components/Input/index.stories.js
  src/theme.js
Labels: first approval, ready for review

#72 fix(Alert): Update spacing and sizing
  src/components/Alert/index.js
  src/components/Input/index.js
  src/components/Toggle/Switch.js
  src/theme.js
Labels: first approval, ready for review

#73 Refactor rem-values
  src/components/Alert/index.js
  src/components/Input/index.js
  src/components/Toggle/Switch.js
Labels: first approval, ready for review

#74 Disable native date input for Android
  src/components/DateInput/index.js
Labels: first approval, ready for review

#75 fix(Image): Handle broken image URLs
  src/components/Image/fetchImage.js
  src/components/Image/index.js
Labels: first approval, ready for review

#76 feat(Icon): Add phone-verified glyph
  src/components/Icon/index.js
Labels: ready for review

#78 fix(Alert): Change padding to margin so it fixes double space issues
  src/components/Alert/index.js
Labels: ready to merge

#77 Add `MoneyInput` component
  .eslintrc
  __tests__/Toast.js
  package-lock.json
  package.json
  src/components/DateInput/index.stories.js
  src/components/Input/index.js
  src/components/MoneyInput/index.js
  src/components/MoneyInput/index.stories.js
  src/components/Select/index.js
  src/index.js
Labels: first approval, ready for review

#79 Animated tab panels
  package-lock.json
  package.json
  src/components/Dialog/index.stories.js
  src/components/TabsGroup/index.js
Labels: ready to merge

#80 fix(MoneyInput): Fix the initial amount and onChange
  src/components/MoneyInput/index.js
  src/components/MoneyInput/index.stories.js
Labels: ready to merge
