Repository TicketSwap/solar, pull requests merged in 2019-07, with the labels that each got.

#217 fix(Checkbox): Lineheight
  src/components/Checkbox/index.js
Labels: first approval, ready for review

#218 fix(Heading): Add a specific line-height var for large sizes
  src/components/Heading/index.js
  src/components/Heading/index.stories.js
  src/theme.js
Labels: first approval, ready for review

#222 fix(InputMenuList): Overflow
  src/components/Input/index.js
Labels: ready to merge

#223 fix(MoneyInput): Make controlled MoneyInput accept null
  src/components/MoneyInput/index.js
  src/components/MoneyInput/index.stories.js
Labels: first approval, ready for review

#231 fix(Spinner): Change animation
  src/components/Spinner/index.js
  src/components/Spinner/index.stories.js
Labels: ready to merge

#233 fix(Checkbox): Allow for long labels
  src/components/Checkbox/index.js
  src/components/Checkbox/index.stories.js
Labels: first approval, ready for review

#241 build(deps-dev): replaced jest-dom with @testing-library/jest-dom
  package.json
  test/jest.client.js
  yarn.lock
Labels: ready for review

#242 feat: Add StarRating component
  __tests__/StarRating.js
  src/components/StarRating/index.js
  src/components/StarRating/index.stories.js
  src/index.js
Labels: first approval, ready for review

#244 refactor: Collocate tests
  jest.config.js
  src/components/Alert/index.test.js
  src/components/Avatar/index.test.js
  src/components/Banner/index.test.js
  src/components/BasicCard/index.test.js
  src/components/CountrySelect/index.test.js
  src/components/Cover/index.test.js
  src/components/Dialog/index.test.js
  src/components/Input/index.test.js
  src/components/MenuButton/index.test.js
  src/components/Select/index.test.js
  src/components/StarRating/index.test.js
  src/components/TabsGroup/index.test.js
  src/components/Toast/index.test.js
  src/utils.js
  src/utils/callAll/index.js
  src/utils/clamp/index.js
  src/utils/clamp/index.test.js
  src/utils/debounce/index.js
  src/utils/index.js
  src/utils/isServer/index.js
  src/utils/stopPropagation/index.js
  test/jest-common.js
Labels: ready to merge

#243 refactor(Alert): Adjust link-color based on alert-variant
  src/components/Alert/index.js
  src/components/Alert/index.stories.js
Labels: first approval, ready for review

#137 Allow image-object for responsive sizes
  src/components/Cover/index.js
  src/components/Cover/index.stories.js
Labels: first approval, ready for review

#245 refactor(StarRating): Fewer divs
  src/components/StarRating/index.js
  src/components/VisuallyHidden/index.js
Labels: ready for review

#246 Update container border radii
  src/components/Banner/index.js
  src/components/Image/index.js
  src/components/Spinner/index.stories.js
Labels: first approval, ready for review

#247 fix(StarRating): Fix markup and remove form-tag
  src/components/StarRating/index.js
  src/components/StarRating/index.stories.js
  src/components/StarRating/index.test.js
Labels: ready for review
