Repository TicketSwap/solar, pull requests merged in 2019-05, with the labels that each got.

#81 Update Facebook icon and colours
  src/components/Button/index.js
  src/components/Icon/index.js
  src/components/Toggle/Switch.js
  src/global-styles.js
  src/theme.js
Labels: ready to merge

#82 Switch to emotion
  .storybook/config.js
  README.md
  __tests__/Alert.js
  __tests__/Input.js
  babel.config.js
  package-lock.json
  package.json
  rollup.config.js
  src/components/Alert/index.js
  src/components/Avatar/index.js
  src/components/Banner/index.js
  src/components/BasicCard/index.js
  src/components/BasicCard/index.stories.js
  src/components/BasicCarousel/index.js
  src/components/BasicCarousel/index.stories.js
  src/components/Button/index.js
  src/components/Card/index.js
  src/components/Carousel/index.js
  src/components/Cover/index.js
  src/components/CustomDropdown/index.js
  src/components/DateInput/index.js
  src/components/Dialog/index.js
  src/components/Flag/index.js
  src/components/Heading/index.js
  src/components/HorizontalScroll/index.js
  src/components/Icon/index.js
  src/components/Image/index.js
  src/components/Input/index.js
  src/components/Logo/index.js
  src/components/MenuButton/index.js
  src/components/MoneyInput/index.js
  src/components/Select/index.js
  src/components/Spinner/index.js
  src/components/Toast/index.js
  src/components/Toggle/Switch.js
  src/components/VisuallyHidden/index.js
  src/global-styles.js
  test/jest.client.js
Labels: first approval, ready for review

#85 build: Switch to Yarn and update deps
  package-lock.json
  package.json
  yarn.lock
Labels: first approval, ready for review

#84 With ContentTransition
  src/components/ContentTransition/index.js
  src/components/ContentTransition/index.stories.js
  src/components/DateInput/index.js
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
  src/components/Select/index.js
  src/components/TabsGroup/index.js
  src/hooks/useKeyPress.js
  src/hooks/useLockBodyScroll.js
Labels: first approval, ready for review

#86 ContentTransition: Add missing export
  src/index.js
Labels: ready for review

#87 Add button variant `caution`
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/components/MoneyInput/index.js
Labels: first approval, ready for review

#88 feat(Input): Add error state to input components
  src/components/Input/index.js
  src/components/Input/index.stories.js
  src/components/MoneyInput/index.js
  src/components/MoneyInput/index.stories.js
Labels: ready to merge

#89 feat(Icon): Add phone icon
  src/components/Icon/index.js
Labels: ready to merge

#90 fix(Flag): Use Image component
  src/components/Flag/index.js
  src/components/Image/index.js
Labels: first approval, ready for review

#91 refactor(Dialog): Update overflow-behaviour
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: first approval, ready for review

#92 fix(DateInput): Fix infinite loop
  src/components/DateInput/index.js
Labels: first approval, ready for review

#93 Add semantic pull request config
  .github/semantic.yml
Labels: first approval, ready for review

#94 fix(ContentTransition): Horizontal overflow-issues
  src/components/ContentTransition/index.js
  src/components/ContentTransition/index.stories.js
  src/components/Dialog/index.js
Labels: first approval, ready for review

#95 fix(BasicCard): Add missing hover-state
  src/components/BasicCard/index.js
Labels: first approval, ready for review

#96 fix(Dialog): Entrance transition
  src/components/Dialog/index.js
Labels: ready for review

#98 fix(Image): Fix Image updating state after unmount
  src/components/Image/index.js
Labels: ready to merge

#99 Money input ref and padded issues
  src/components/DateInput/index.js
Labels: ready to merge

#100 refactor(Select): Conditionally render option adornment
  src/components/Select/index.js
Labels: ready for review

#101 Remove express dependency
  package.json
  yarn.lock
Labels: first approval, ready for review

#102 With Comets
  __tests__/Dialog.js
  package.json
  src/components/Alert/index.js
  src/components/Banner/index.js
  src/components/BasicCarousel/index.js
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/components/ContentTransition/index.stories.js
  src/components/CountrySelect/index.js
  src/components/Dialog/index.stories.js
  src/components/Icon/index.js
  src/components/Input/index.js
  src/components/Input/index.stories.js
  src/components/Select/index.js
  src/components/Spinner/index.js
  yarn.lock
Labels: first approval, ready for review

#103 fix(DateInput): Only allow numbers for day and year inputs
  src/components/DateInput/index.js
Labels: ready to merge

#104 Revert "Merge pull request #102 from TicketSwap/with-comets"
  __tests__/Dialog.js
  package.json
  src/components/Alert/index.js
  src/components/Banner/index.js
  src/components/BasicCarousel/index.js
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/components/ContentTransition/index.stories.js
  src/components/CountrySelect/index.js
  src/components/Dialog/index.stories.js
  src/components/Icon/index.js
  src/components/Input/index.js
  src/components/Input/index.stories.js
  src/components/Select/index.js
  src/components/Spinner/index.js
  yarn.lock
Labels: ready for review

#105 fix(DateInput): Fix setting of the date input
  src/components/DateInput/index.js
Labels: ready for review

#106 Revert #104 to add back Comets
  __tests__/Dialog.js
  package.json
  src/components/Alert/index.js
  src/components/Banner/index.js
  src/components/BasicCarousel/index.js
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/components/ContentTransition/index.stories.js
  src/components/CountrySelect/index.js
  src/components/Dialog/index.stories.js
  src/components/Icon/index.js
  src/components/Input/index.js
  src/components/Input/index.stories.js
  src/components/Select/index.js
  src/components/Spinner/index.js
  yarn.lock
Labels: first approval, ready for review

#107 Update lint-staged and Husky config
  .huskyrc
  husky.config.js
Labels: first approval, ready for review

#109 fix: Update comets to v1.1.1
  package.json
  yarn.lock
Labels: ready for review

#112 Add skeleton components
  src/components/BasicCard/index.js
  src/components/Image/index.js
  src/components/Skeleton/index.js
  src/index.js
Labels: first approval, ready for review

#108 Add Checkbox component
  README.md
  package.json
  src/components/Checkbox/index.js
  src/components/Checkbox/index.stories.js
  src/index.js
Labels: first approval, ready for review

#136 fix(Dialog): Fix defaultOn behaviour
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: ready for review
