Repository TicketSwap/solar, pull requests merged in 2019-01, with the labels that each got.

#1 Fix onClick handler in MenuButton component
  dist/solar.es.js
  dist/solar.js
  src/components/MenuButton/index.js
  src/components/MenuButton/index.stories.js
Labels: first approval

#2 Test MenuButton component
  __mocks__/react-spring/Transition.js
  __mocks__/react-spring/index.js
  __tests__/MenuButton.js
Labels: ready to merge

#3 Export static Storybook build
  .prettierignore
  docs/favicon.ico
  docs/iframe.html
  docs/index.html
  docs/main.5a1c8ed84268b375a676.bundle.js
  docs/main.5a1c8ed84268b375a676.bundle.js.map
  docs/main.95b5f8b65d86a0e0744e.bundle.js
  docs/runtime~main.5a1c8ed84268b375a676.bundle.js
  docs/runtime~main.5a1c8ed84268b375a676.bundle.js.map
  docs/runtime~main.729a62daeea60911f9f0.bundle.js
  docs/sb_dll/storybook_ui-manifest.json
  docs/sb_dll/storybook_ui_dll.LICENCE
  docs/sb_dll/storybook_ui_dll.js
  docs/vendors~main.51e969a636c75a8f15dd.bundle.js
  docs/vendors~main.5a1c8ed84268b375a676.bundle.js
  docs/vendors~main.5a1c8ed84268b375a676.bundle.js.map
  package-lock.json
  package.json
  test/jest-common.js
  test/jest.lint.js
Labels: first approval, ready for review

#4 Install storybook-deployer
  .eslintignore
  .prettierignore
  docs/favicon.ico
  docs/iframe.html
  docs/index.html
  docs/main.5a1c8ed84268b375a676.bundle.js
  docs/main.5a1c8ed84268b375a676.bundle.js.map
  docs/main.95b5f8b65d86a0e0744e.bundle.js
  docs/runtime~main.5a1c8ed84268b375a676.bundle.js
  docs/runtime~main.5a1c8ed84268b375a676.bundle.js.map
  docs/runtime~main.729a62daeea60911f9f0.bundle.js
  docs/sb_dll/storybook_ui-manifest.json
  docs/sb_dll/storybook_ui_dll.LICENCE
  docs/sb_dll/storybook_ui_dll.js
  docs/vendors~main.51e969a636c75a8f15dd.bundle.js
  docs/vendors~main.5a1c8ed84268b375a676.bundle.js
  docs/vendors~main.5a1c8ed84268b375a676.bundle.js.map
  package-lock.json
  package.json
Labels: first approval, ready for review

#6 Add bottom margin to Input label
  src/components/Input/index.js
Labels: first approval, ready for review

#7 Normalise border radii across components
  src/components/Alert/index.js
  src/components/Banner/index.js
  src/components/Button/index.js
  src/components/CustomDropdown/index.js
  src/components/Dialog/index.js
  src/components/Input/index.js
  src/components/Toast/index.js
  src/theme.js
Labels: first approval, ready for review

#9 Use terser for bundle minification
  package-lock.json
  package.json
  rollup.config.js
Labels: first approval, ready for review

#10 Fix auto-fill state for Input components
  src/components/Box/index.js
  src/components/Input/index.js
Labels: first approval, ready for review

#11 Allow persistent dialogs
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: ready to merge

#12 Update Input component
  package-lock.json
  package.json
  src/components/Input/index.js
  src/components/Input/index.stories.js
Labels: ready to merge

#13 fix(Input): Fix default webkit input appearance
  jest.config.js
  src/components/Input/index.js
  src/components/Input/index.stories.js
Labels: first approval, ready for review

#14 Disable hyphenation for input and textarea elements
  src/components/Input/index.js
  src/global-styles.js
Labels: ready to merge

#17 Add Spotify icon
  src/components/Icon/index.js
Labels: first approval, ready for review
