Repository TicketSwap/solar, pull requests merged in 2019-08, with the labels that each got.

#265 fix(banner): change component type
  src/components/Banner/index.js
Labels: ready to merge

#266 feat(logo): add LGBT variant
  src/components/Logo/Path.js
  src/components/Logo/index.js
  src/components/Logo/index.stories.js
Labels: first approval, ready for review

#264 fix(MoneyInput): parse initial value with at least 2 decimals
  src/components/MoneyInput/index.js
  src/components/MoneyInput/index.stories.js
Labels: ready to merge

#274 feat: add TimeInput component
  src/components/TimeInput/index.js
  src/components/TimeInput/index.stories.js
  src/components/TimeInput/index.test.js
  src/index.js
Labels: ready for review

#295 refactor(dialog): build render-prop API with useDialog
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: first approval, ready for review

#297 Fix conflicting ID’s in custom input components
  package.json
  src/components/DateInput/index.js
  src/components/MoneyInput/index.js
  src/components/PhoneInput/index.js
  yarn.lock
Labels: first approval, ready for review

#298 Update deps
  package.json
  yarn.lock
Labels: ready for review

#299 fix(dialog): fix prop destructuring of useDialog hook
  src/components/Dialog/index.js
Labels: ready for review

#300 feat(toast): add useToast() hook
  src/components/Toast/index.js
  src/components/Toast/index.stories.js
  src/index.js
Labels: first approval, ready for review

#301 fix(heading): update H2 font-weight
  src/components/Heading/index.js
Labels: ready for review

#309 chore: update deps
  package.json
  yarn.lock
Labels: ready for review
