Repository TicketSwap/solar, pull requests merged in 2019-02, with the labels that each got.

#19 Update basic global styles
  src/global-styles.js
Labels: ready to merge

#20 Update global CSS reset
  .storybook/config.js
  .storybook/preview-head.html
  src/components/Alert/index.js
  src/components/Banner/index.js
  src/components/CustomDropdown/index.js
  src/components/Heading/index.js
  src/global-styles.js
  src/index.js
Labels: first approval, ready for review

#21 Add loupe icon
  src/components/Icon/index.js
Labels: ready for review

#22 Address max-height issues with Dialog component
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: ready to merge

#23 fix(Dialog): Address wrong flex-shrink behaviour in Firefox
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: first approval, ready for review

#25 Update npm dependencies
  package-lock.json
  package.json
Labels: ready for review

#24 Revert max-height handling in Dialog
  src/components/Dialog/index.js
Labels: ready for review

#26 fix(Button): Set default hover text color for the Button component
  src/components/Button/index.js
Labels: ready to merge

#27 Update dialog component
  package-lock.json
  package.json
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: first approval, ready for review

#29 Update Rollup config and only export ES bundle
  package-lock.json
  package.json
  rollup.config.js
Labels: first approval, ready for review

#28 fix(Input): Add display block to styled label
  src/components/Input/index.js
Labels: ready to merge

#30 Add back globals object in Rollup config
  rollup.config.js
Labels: first approval, ready for review

#31 Fix Rollup bundle config
  package-lock.json
  package.json
  rollup.config.js
Labels: first approval, ready for review

#32 Disable bundle minification
  package-lock.json
  package.json
  rollup.config.js
Labels: first approval, ready for review

#34 Refactor Box component usage in Banner and Card
  src/components/Banner/index.js
  src/components/BasicCard/index.stories.js
  src/components/Box/index.stories.js
  src/components/Button/index.stories.js
  src/components/Card/index.js
  src/components/Dialog/index.stories.js
  src/components/Image/index.stories.js
  src/components/MenuButton/index.stories.js
  src/components/Toast/index.stories.js
Labels: ready to merge

#35 Remove Box component
  src/components/Box/index.js
  src/index.js
Labels: ready to merge

#33 Refactor dialog
  package-lock.json
  package.json
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
  src/hooks/index.js
  src/hooks/useLockBodyScroll.js
  src/index.js
Labels: ready to merge

#36 Address resetting of carousels on mobile devices
  src/components/Carousel/index.js
Labels: first approval, ready for review

#37 fix(Carousel): Typo
  src/components/Carousel/index.js
Labels: ready for review

#38 Optimise image loading
  babel.config.js
  package-lock.json
  package.json
  src/components/Flag/index.js
  src/components/Image/fetchImage.js
  src/components/Image/index.js
Labels: first approval, ready for review

#39 Change async arrow fn to avoid bug in Safari
  src/components/Image/index.js
Labels: first approval, ready for review

#40 Update `react-spring`
  __mocks__/react-spring/renderprops/Spring.js
  __mocks__/react-spring/renderprops/Transition.js
  __mocks__/react-spring/renderprops/index.js
  package-lock.json
  package.json
  src/components/BasicCarousel/index.js
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
  src/components/MenuButton/index.js
  src/components/Toast/index.js
Labels: first approval, ready for review

#42 Check if window.matchMedia() is available
  src/components/Carousel/index.js
  src/components/Dialog/index.js
Labels: first approval, ready for review

#43 Pass initial `on` state correctly
  src/components/Dialog/index.js
Labels: first approval, ready for review

#44 fix(Alert): Fix spreading of all props to sub components
  src/components/Alert/index.js
Labels: ready to merge

#45 Refactor MenuButton
  __tests__/MenuButton.js
  package-lock.json
  package.json
  src/components/CustomDropdown/index.js
  src/components/MenuButton/index.js
  src/components/MenuButton/index.stories.js
  src/hooks/index.js
  src/hooks/useKeyPress.js
  src/hooks/useOnClickOutside.js
  src/hooks/usePrevious.js
  src/index.js
Labels: first approval, ready for review
