Repository TicketSwap/solar, pull requests merged in 2020-02, with the labels that each got.

#589 feat(Dialog): Add transition callbacks
  src/components/Dialog/index.js
  src/components/Dialog/index.stories.js
Labels: first approval, ready for review

#590 fix(Toggle): Support loading state
  src/components/Toggle/Switch.js
  src/components/Toggle/index.stories.js
Labels: first approval, ready for review

#591 fix(Toggle): Don’t spread wrong props on HTML element
  src/components/Toggle/Switch.js
Labels: ready for review

#592 fix(Toggle): Adornment markup
  src/components/Toggle/Switch.js
Labels: ready for review

#593 fix(Toggle): Adornment positioning
  src/components/Toggle/Switch.js
Labels: ready for review

#601 fix(Card): Subtitle spacing
  src/components/Card/index.js
Labels: ready for review

#602 Add description prop to Card component
  src/components/Card/index.js
  src/components/Card/index.stories.js
Labels: first approval, ready for review

#603 fix(Pill): Add missing disabled variant
  src/components/Pill/index.js
  src/components/Pill/index.stories.js
Labels: ready for review

#607 fix(Card): Adjust text truncating and line-height
  src/components/Card/index.js
  src/components/Card/index.stories.js
Labels: ready for review

#608 fix: adjust accordion button
  src/components/Accordion/index.js
Labels: first approval, ready for review

#609 fix(Toggle): ARIA attributes
  src/components/Toggle/index.js
Labels: ready for review

#617 fix(moneyiput): fix MoneyInput rounding issue
  src/components/MoneyInput/index.js
  src/components/MoneyInput/index.stories.js
Labels: ready to merge

#618 fix: Accordion button padding
  src/components/Accordion/index.js
Labels: first approval, ready for review

#619 feat(BaseButton): Add leftAdornment
  src/components/BaseButton/index.js
  src/components/BaseButton/index.stories.js
Labels: first approval, ready for review

#620 Add SpeechBubble
  src/components/SpeechBubble/index.js
  src/components/SpeechBubble/index.stories.js
Labels: ready to merge

#621 Export SpeechBubble
  src/index.js
Labels: first approval, ready for review

#622 fix(SpeechBubble): Use children instead of label
  src/components/SpeechBubble/index.js
  src/components/SpeechBubble/index.stories.js
Labels: first approval, ready for review

#623 fix(Accordion): Bottom padding on panel
  src/components/Accordion/index.js
Labels: ready for review
