Repository TicketSwap/solar, pull requests merged in 2020-01, with the labels that each got.

#520 fix(Card): Use title for image alt-text
  src/components/Card/index.js
Labels: first approval, ready for review

#521 MoneyInput > Disable select as well when MoneyInput is disabled
  src/components/MoneyInput/index.js
  src/components/MoneyInput/index.stories.js
  src/components/Select/index.js
Labels: first approval, ready for review

#538 fix(StarRating): Update active color
  src/components/StarRating/index.js
Labels: ready for review

#567 Toggle: Support adornments
  src/components/Toggle/Switch.js
  src/components/Toggle/index.js
  src/components/Toggle/index.stories.js
Labels: first approval, ready for review

#568 fix: rename SelectWithSearch to Combobox
  src/components/Combobox/index.js
  src/components/Combobox/index.stories.js
  src/components/Combobox/index.test.js
  src/index.js
Labels: ready to merge

#569 fix: Invalid proptype in combobox
  src/components/Combobox/index.js
Labels: ready to merge

#571 feat(Alert): Add new title prop
  src/components/Alert/index.js
  src/components/Alert/index.stories.js
Labels: first approval, ready for review
