Repository TicketSwap/solar, pull requests merged in 2021-11, with the labels that each got.

#1244 feat(Button): Add google variant
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
Labels: ready for review

#1236 docs(guidelines): adding general guidelines
  .storybook/main.js
  .storybook/preview.js
  docs/Guidelines/Brand/brand.stories.mdx
  docs/Guidelines/Colors/ColorComponent.tsx
  docs/Guidelines/Colors/ColorDefinitions.tsx
  docs/Guidelines/Colors/Colors.tsx
  docs/Guidelines/Colors/PrintAndDigital.tsx
  docs/Guidelines/Colors/colors.stories.mdx
  docs/Guidelines/Colors/data.tsx
  docs/Guidelines/GettingStarted/gettingstarted.stories.mdx
  docs/Guidelines/Logo/Logos.tsx
  docs/Guidelines/Logo/logo.stories.mdx
  src/tokens/colors/Earth/index.stories.tsx
  src/tokens/colors/Mars/index.stories.tsx
  src/tokens/colors/Nova/index.stories.tsx
  src/tokens/colors/Sky/index.stories.tsx
  src/tokens/colors/Socials/index.stories.tsx
  src/tokens/colors/Space/index.stories.tsx
  src/tokens/colors/Stardust/index.stories.tsx
  src/tokens/colors/Sun/index.stories.tsx
  src/tokens/colors/Titan/index.stories.tsx
Labels: ready to merge

#1253 feat(onetimecodeinput): added a OneTimeCodeInput field
  package.json
  src/components/OneTimeCodeInput/index.stories.tsx
  src/components/OneTimeCodeInput/index.test.tsx
  src/components/OneTimeCodeInput/index.tsx
  src/components/index.ts
  yarn.lock
Labels: ready to merge

#1245 Improve Select rendering of mobile version
  src/components/Select/index.test.tsx
  src/components/Select/index.tsx
Labels: ready to merge

#1266 Refactor(horizontalscroll): removal of unecessary/deprecated css
  src/components/HorizontalScroll/index.tsx
Labels: first approval, ready for review

#1267 Don't collect test coverage from Storybook stories
  jest.config.js
Labels: ready to merge
