Repository TicketSwap/solar, pull requests merged in 2021-04, with the labels that each got.

#1089 feat(phoneinput): make it possible to have a controlled PhoneInput
  src/components/PhoneInput/index.stories.tsx
  src/components/PhoneInput/index.tsx
Labels: ready to merge

#1092 feat(theme): added 40px and 88px space sizes & 22px fontSize
  src/theme.ts
Labels: first approval, ready for review

#1099 fix(button): fix dark mode background color of caution variant
  src/components/Button/index.tsx
Labels: ready for review

#1102 fix(CardCarousel): fix colors of the card carousel controls
  src/components/CardCarousel/index.tsx
Labels: ready for review

#1103 feat(dialog): dialog backdrop with blur and different color
  src/components/ContentDialog/index.tsx
  src/components/Dialog/index.tsx
Labels: first approval, ready for review
