Repository TicketSwap/solar, pull requests merged in 2022-09, with the labels that each got.

#1596 fix(useTransition): fix types output for useTransition
  src/hooks/useTransition/index.ts
Labels: ready for review

#1607 fix: Made gradient backdrop for cards with images stronger to make sure text remains readable
  src/components/Card/index.tsx
Labels: first approval, ready for review

#1589 Changed some usages of the palette colors to semantic variants
  src/components/ContentTransition/index.stories.tsx
  src/components/DatePicker/Day.tsx
  src/components/Logo/index.stories.tsx
  src/components/Pill/index.tsx
  src/components/RadioGroup/Radio.tsx
  src/components/Toast/index.stories.tsx
  src/global-styles.ts
Labels: first approval, ready for review

#1622 fix(select): fix width on mobile
  src/components/SelectV2/Select.tsx
Labels: ready to merge
