Repository TicketSwap/solar, pull requests merged in 2022-02, with the labels that each got.

#1338 Avatar src can be nullable
  src/components/Avatar/index.tsx
Labels: first approval, ready for review

#1346 Fix ContentDialogHeader title color in dark mode
  src/components/ContentDialog/index.tsx
Labels: ready to merge

#1356 Replace Semantic Pull Request app for action
  .github/semantic.yml
  .github/workflows/ci.yml
Labels: first approval, ready for review

#1355 Introduce ExternalLink icon
  docs/Guidelines/Iconography/Icons.tsx
  src/icons/ExternalLink.tsx
  src/icons/index.tsx
Labels: ready to merge

#1357 Allow commit messages to start with uppercase character
  commitlint.config.js
  package.json
  yarn.lock
Labels: first approval, ready for review

#1353 feat(datePicker): allowing to hide frontAdornment
  src/components/DatePicker/index.stories.tsx
  src/components/DatePicker/index.tsx
Labels: ready to merge

#1364 ci(commitlint.config.js): override body-max-line-length rule
  commitlint.config.js
Labels: first approval, ready for review

#1358 Toast: add left adornment on toast component
  src/components/Toast/index.stories.tsx
  src/components/Toast/index.test.tsx
  src/components/Toast/index.tsx
Labels: ready to merge

#1366 feat(Icons): Add Tidal icon
  docs/Guidelines/Iconography/Icons.tsx
  src/icons/Tidal.tsx
  src/icons/index.tsx
Labels: ready for review

#1378 Use yarn commands in package.json
  package.json
Labels: first approval, ready for review
