Repository TicketSwap/solar, pull requests merged in 2022-11, with the labels that each got.

#1655 Add missing title and back props to DialogBody
  src/components/Dialog/index.stories.tsx
  src/components/Dialog/index.tsx
Labels: ready to merge

#1664 File type checking dropzone
  src/components/Dropzone/Dropzone.tsx
Labels: first approval, ready for review

#1656 Add check if option or currentOption exists
  src/components/SelectV2/Select.tsx
Labels: ready to merge

#1665 chore(Panel): replace shadow with stroke
  src/components/Panel/index.tsx
Labels: first approval, ready for review, ready to merge

#1668 SelectV2 - Fix React warning for default value
  src/components/SelectV2/Select.tsx
Labels: first approval, ready for review
