Repository TicketSwap/solar, pull requests merged in 2023-04, with the labels that each got.

#1716 fix(Dropzone): Re-add border
  src/components/Dropzone/Dropzone.tsx
Labels: ready to merge

#1717 fix(Toast): fix re-render issues of notify
  src/components/Toast/index.stories.tsx
  src/components/Toast/index.tsx
Labels: ready for review

#1720 feat(Cover): Make it possible to pass ReactElement as subtitle
  src/components/CoverV2/Cover.tsx
Labels: ready for review

#1721 feat(theme): make theme properties readonly
  src/theme.ts
Labels: ready for review

#1722 fix(theme): Fixed odd shadow/overlay colors in theme
  src/global-styles.ts
  src/theme.ts
Labels: first approval, ready for review
