Repository TicketSwap/solar, pull requests merged in 2023-08, with the labels that each got.

#1774 feat(global): switch to media queries for prefered color scheme
  src/components/Button/index.tsx
  src/components/Cover/index.tsx
  src/components/CoverV2/Cover.tsx
  src/components/Input/index.tsx
  src/components/OnboardingDialog/index.tsx
  src/components/Skeleton/index.tsx
  src/components/SpeechBubble/index.tsx
  src/global-styles.ts
Labels: first approval, ready for review, hold deploy

#1777 fix: revert @reach/tooltip update
  package.json
  yarn.lock
Labels: first approval, ready for review

#1779 feat(Toast): rename displayLength to duration
  src/components/Toast/index.stories.tsx
  src/components/Toast/index.tsx
Labels: first approval, ready for review

#1780 feat(CoverV2): Add tag as property
  src/components/CoverV2/Cover.tsx
  src/components/CoverV2/index.stories.tsx
Labels: ready for review

#1712 docs(typing): add types to color definitions
  docs/Guidelines/Colors/ColorDefinitions.tsx
Labels: first approval, ready for review

#1786 build(build): force minimum node version 18
  package.json
Labels: first approval, ready for review

#1787 fix(BaseButton): use action color instead of info color
  src/components/BaseButton/index.tsx
Labels: ready for review

#1792 Introduce RadioPanel component
  src/components/RadioGroup/Radio.tsx
  src/components/RadioGroup/RadioPanel.tsx
  src/components/RadioGroup/index.stories.tsx
  src/components/RadioGroup/index.tsx
  src/components/index.ts
Labels: first approval, ready for review
