Repository TicketSwap/solar, pull requests merged in 2023-01, with the labels that each got.

#1695 fix(datePicker): corrected first day of the year in calendar
  src/components/DatePicker/CalendarDialog.tsx
Labels: ready to merge

#1697 fix(chip): fix style element showing when styled start adornment is used
  src/components/Chip/Chip.tsx
Labels: ready for review

#1661 feat: Add light variant to Dropzone
  src/components/Dropzone/Dropzone.tsx
  src/components/Dropzone/index.stories.tsx
Labels: first approval, ready for review

#1698 fix: Allow Dropzone to be used in forms
  src/components/BaseButton/index.tsx
  src/components/Dropzone/Dropzone.tsx
Labels: ready to merge
